In [6]:
import os
import pandas as pd

# Lấy thư mục hiện tại chứa notebook
notebook_dir = os.path.dirname(os.path.abspath('__file__'))

# Trỏ đến tệp CSV
train_path = os.path.join(notebook_dir, 'data.csv')
train_df = pd.read_csv(train_path)

In [7]:
train_columns = train_df.columns.to_list()
train_columns[1:] = [f"col_{i}" for i in range(1, len(train_columns))]
train_columns

['id',
 'col_1',
 'col_2',
 'col_3',
 'col_4',
 'col_5',
 'col_6',
 'col_7',
 'col_8',
 'col_9',
 'col_10']

In [8]:
train_df.columns = train_columns
train_df.head()

,id,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10
0,577347,120.719779,23.924249,23.668066,21.951680,21.086183,20.180032,19.202124,0.429042,G/K,Red_Sequence
1,577348,219.414419,42.171651,24.902933,22.338822,20.732163,19.860330,19.687691,0.867305,M,Red_Sequence
2,577349,173.568731,-1.756400,19.427591,18.474633,17.551314,16.570674,16.176765,0.224234,G/K,Blue_Cloud
3,577350,184.903993,-1.411074,23.121029,21.526855,20.670159,20.417633,20.699095,0.066507,G/K,Red_Sequence
4,577351,222.487816,15.381403,25.094282,22.643981,21.123173,19.439500,19.094158,0.977218,M,Red_Sequence

In [9]:
for col in train_df.columns.to_list():
    if train_df[col].dtype in ["object", "category", "str"]:
        codes, _ = pd.factorize(train_df[col])
        train_df[col] = codes

train_df.head()

,id,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10
0,577347,120.719779,23.924249,23.668066,21.951680,21.086183,20.180032,19.202124,0.429042,0,0
1,577348,219.414419,42.171651,24.902933,22.338822,20.732163,19.860330,19.687691,0.867305,1,0
2,577349,173.568731,-1.756400,19.427591,18.474633,17.551314,16.570674,16.176765,0.224234,0,1
3,577350,184.903993,-1.411074,23.121029,21.526855,20.670159,20.417633,20.699095,0.066507,0,0
4,577351,222.487816,15.381403,25.094282,22.643981,21.123173,19.439500,19.094158,0.977218,1,0

In [10]:
output_path = os.path.join(notebook_dir, 'processed_data.csv')
train_df.to_csv(output_path, index = False)
print(f"Saved processed dataframe to {output_path}")

Saved processed dataframe to d:\Research\tabular-transformation\notebooks\processed_data.csv